/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_peluqueria;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class ClientesView extends javax.swing.JFrame {

    private ClienteDAO clienteDAO;
    private DefaultTableModel model;

    /**
     * Creates new form ClientesView
     */
    public ClientesView() {
        initComponents();
        btnActualizar.setVisible(false);
        txt_idCliente.setEnabled(false);
        txt_idCliente.setVisible(false);
        lbl_idCliente.setVisible(false);
        btnEliminar.setVisible(false);
        setLocationRelativeTo(null);
        cargarClientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        lbl_idCliente = new java.awt.Label();
        txt_idCliente = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listaClientes = new javax.swing.JTable();
        lbl_rucCliente = new java.awt.Label();
        lbl_telefonoCliente = new java.awt.Label();
        txt_telefonoCliente = new java.awt.TextField();
        txt_rucCliente = new java.awt.TextField();
        btnAñadir = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        btnEliminar = new javax.swing.JButton();
        lbl_nombreCliente = new java.awt.Label();
        txt_nombresCliente = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        lbl_idCliente.setText("ID:");

        txt_idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idClienteActionPerformed(evt);
            }
        });

        tbl_listaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUC", "Nombre y Apellido", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_listaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_listaClientes);

        lbl_rucCliente.setText("RUC: ");

        lbl_telefonoCliente.setText("Teléfono:");

        txt_telefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoClienteActionPerformed(evt);
            }
        });

        txt_rucCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_rucCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rucClienteActionPerformed(evt);
            }
        });

        btnAñadir.setText("Añadir");
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });

        label1.setText("REGISTRO DE CLIENTES");
        label1.setVisible(false);

        label2.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        label2.setText("REGISTRO DE CLIENTES");

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lbl_nombreCliente.setText("Nombre y Apellido:");

        txt_nombresCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnEliminar)
                            .addGap(18, 18, 18)
                            .addComponent(btnActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAñadir))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_telefonoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_rucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_rucCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_telefonoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_nombresCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                    .addComponent(txt_idCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))
                                .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombreCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombresCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_rucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rucClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rucClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rucClienteActionPerformed

    private void txt_telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoClienteActionPerformed

    private void txt_idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_idClienteActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        eliminarCliente();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
        System.out.println("se dio click");
        agregarCliente();
    }//GEN-LAST:event_btnAñadirMouseClicked

    private void tbl_listaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listaClientesMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada = tbl_listaClientes.rowAtPoint(evt.getPoint());
        txt_idCliente.setText(String.valueOf(tbl_listaClientes.getValueAt(fila_seleccionada, 0)));
        txt_rucCliente.setText(String.valueOf(tbl_listaClientes.getValueAt(fila_seleccionada, 1)));
        txt_nombresCliente.setText(String.valueOf(tbl_listaClientes.getValueAt(fila_seleccionada, 2)));
        txt_telefonoCliente.setText(String.valueOf(tbl_listaClientes.getValueAt(fila_seleccionada, 3)));
        btnActualizar.setVisible(true);
        btnEliminar.setVisible(true);
        btnAñadir.setVisible(false);
        txt_idCliente.setVisible(true);
        lbl_idCliente.setVisible(true);
    }//GEN-LAST:event_tbl_listaClientesMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txt_nombresClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresClienteActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        actualizarCliente();

    }//GEN-LAST:event_btnActualizarMouseClicked

    

    private void cargarClientes() {
        String[] columnNames = {"ID", "RUC", "Nombre", "Teléfono"};
        model = new DefaultTableModel(columnNames, 0);
        clienteDAO = new ClienteDAO();

        List<Cliente> clientes = new ArrayList<>();
        clientes = clienteDAO.obtenerTodosClientes();
        for (Cliente cliente : clientes) {
            model.addRow(new Object[]{cliente.getId_cliente(), cliente.getRUC_cliente(), cliente.getNombre_cliente(), cliente.getTelefono_cliente()});
            System.out.println(cliente.getId_cliente() + "\t" + cliente.getRUC_cliente() + "\t" + cliente.getNombre_cliente() + "\t" + cliente.getTelefono_cliente());
        }
        tbl_listaClientes.setModel(model);

    }

    private void limpiarCampos() {
        txt_idCliente.setText("");
        txt_nombresCliente.setText("");
        txt_rucCliente.setText("");
        txt_telefonoCliente.setText("");

    }

    private void agregarCliente() {
        try {
            String RUC = txt_rucCliente.getText();
            String nombre = txt_nombresCliente.getText();
            String telefono = txt_telefonoCliente.getText();

            Cliente nuevoCliente = new Cliente(0, RUC, nombre, telefono);
            if (clienteDAO.agregarCliente(nuevoCliente)) {
                cargarClientes();
                limpiarCampos();
                //Muestra una ventana de dialogo con el mensaje 
                JOptionPane.showMessageDialog(null, "Se agregó el cliente correctamente");
            } else {
                //Muestra una ventana de dialogo con el mensaje
                JOptionPane.showMessageDialog(null, "No se pudo agregar el cliente");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void actualizarCliente() {
        int id = Integer.parseInt(txt_idCliente.getText());
        String RUC = txt_rucCliente.getText();
        String nombre = txt_nombresCliente.getText();
        String telefono = txt_telefonoCliente.getText();

        Cliente clienteActualizado = new Cliente(id, RUC, nombre, telefono);
        if (clienteDAO.actualizarCliente(clienteActualizado)) {
            cargarClientes();
            limpiarCampos();
            btnActualizar.setVisible(false);
            btnAñadir.setVisible(true);
            lbl_idCliente.setVisible(false);
            txt_idCliente.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se actualizó el cliente correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el cliente");
        }

    }

    private void eliminarCliente() {
        int id = Integer.parseInt(txt_idCliente.getText());
        if (clienteDAO.eliminarCliente(id)) {
            cargarClientes();
            limpiarCampos();
            btnActualizar.setVisible(false);
            btnAñadir.setVisible(true);
            btnEliminar.setVisible(false);
            lbl_idCliente.setVisible(false);
            txt_idCliente.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se eliminó el cliente correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el cliente");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label lbl_idCliente;
    private java.awt.Label lbl_nombreCliente;
    private java.awt.Label lbl_rucCliente;
    private java.awt.Label lbl_telefonoCliente;
    private javax.swing.JTable tbl_listaClientes;
    private java.awt.TextField txt_idCliente;
    private java.awt.TextField txt_nombresCliente;
    private java.awt.TextField txt_rucCliente;
    private java.awt.TextField txt_telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
