/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_peluqueria;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class EmpleadosView extends javax.swing.JFrame {

    private EmpleadoDAO empleadoDAO;
    private DefaultTableModel model;

    /**
     * Creates new form EmpleadosView
     */
    public EmpleadosView() {
        initComponents();
        btn_actualizarEmpleado.setVisible(false);
        txt_idEmpleado.setEnabled(false);
        txt_idEmpleado.setVisible(false);
        lbl_idEmpleado.setVisible(false);
        btn_eliminarEmpleado.setVisible(false);
        setLocationRelativeTo(null);
        cargarEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        lbl_idEmpleado = new java.awt.Label();
        lbl_nombresEmpleado = new java.awt.Label();
        lbl_rucEmpleado = new java.awt.Label();
        label5 = new java.awt.Label();
        txt_idEmpleado = new java.awt.TextField();
        txt_nombresEmpleado = new java.awt.TextField();
        txt_rucEmpleados = new java.awt.TextField();
        txt_telefonoEmpleado = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listaEmpleados = new javax.swing.JTable();
        lbl_telefonoEmpleado = new java.awt.Label();
        btn_añadirEmpleado = new javax.swing.JButton();
        btn_actualizarEmpleado = new javax.swing.JButton();
        btn_eliminarEmpleado = new javax.swing.JButton();
        btn_regresarEmpleados = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        label1.setText("REGISTRO EMPLEADOS");

        lbl_idEmpleado.setText("ID:");

        lbl_nombresEmpleado.setText("Nombre y Apellido:");

        lbl_rucEmpleado.setText("RUC/Cédula:");

        label5.setText("Teléfono:");
        label5.setVisible(false);

        tbl_listaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RUC", "Nombre y Apellido", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_listaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_listaEmpleados);

        lbl_telefonoEmpleado.setText("Telefono:");

        btn_añadirEmpleado.setText("Añadir");
        btn_añadirEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirEmpleadoMouseClicked(evt);
            }
        });

        btn_actualizarEmpleado.setText("Actualizar");
        btn_actualizarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarEmpleadoMouseClicked(evt);
            }
        });

        btn_eliminarEmpleado.setText("Eliminar");
        btn_eliminarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarEmpleadoMouseClicked(evt);
            }
        });
        btn_eliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarEmpleadoActionPerformed(evt);
            }
        });

        btn_regresarEmpleados.setLabel("Regresar");
        btn_regresarEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarEmpleadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_regresarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_nombresEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_rucEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbl_telefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(52, 52, 52)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_nombresEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                        .addComponent(txt_rucEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_telefonoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_idEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_eliminarEmpleado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_actualizarEmpleado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_añadirEmpleado))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_nombresEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nombresEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_rucEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rucEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_telefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_añadirEmpleado)
                    .addComponent(btn_actualizarEmpleado)
                    .addComponent(btn_eliminarEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_regresarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarEmpleadoActionPerformed

    private void btn_eliminarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarEmpleadoMouseClicked
        // TODO add your handling code here:
        eliminarEmpleado();
    }//GEN-LAST:event_btn_eliminarEmpleadoMouseClicked

    private void btn_actualizarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarEmpleadoMouseClicked
        // TODO add your handling code here:
        actualizarEmpleado();
    }//GEN-LAST:event_btn_actualizarEmpleadoMouseClicked

    private void btn_añadirEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirEmpleadoMouseClicked
        // TODO add your handling code here:
        agregarEmpleado();
    }//GEN-LAST:event_btn_añadirEmpleadoMouseClicked

    private void tbl_listaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listaEmpleadosMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada = tbl_listaEmpleados.rowAtPoint(evt.getPoint());
        txt_idEmpleado.setText(String.valueOf(tbl_listaEmpleados.getValueAt(fila_seleccionada, 0)));
        txt_rucEmpleados.setText(String.valueOf(tbl_listaEmpleados.getValueAt(fila_seleccionada, 1)));
        txt_nombresEmpleado.setText(String.valueOf(tbl_listaEmpleados.getValueAt(fila_seleccionada, 2)));
        txt_telefonoEmpleado.setText(String.valueOf(tbl_listaEmpleados.getValueAt(fila_seleccionada, 3)));
        btn_actualizarEmpleado.setVisible(true);
        btn_eliminarEmpleado.setVisible(true);
        btn_añadirEmpleado.setVisible(false);
        txt_idEmpleado.setVisible(true);
        lbl_idEmpleado.setVisible(true);
    }//GEN-LAST:event_tbl_listaEmpleadosMouseClicked

    private void btn_regresarEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarEmpleadosMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_regresarEmpleadosMouseClicked

    private void cargarEmpleado() {
        String[] columnNames = {"ID", "RUC", "Nombre", "Teléfono"};
        model = new DefaultTableModel(columnNames, 0);
        empleadoDAO = new EmpleadoDAO();

        List<Empleado> empleados = new ArrayList<>();
        empleados = empleadoDAO.obtenerTodosEmpleados();
        for (Empleado empleado : empleados) {
            model.addRow(new Object[]{empleado.getId_empleado(), empleado.getRUC_empleado(), empleado.getNombre_empleado(), empleado.getTelefono_empleado()});
            System.out.println(empleado.getId_empleado() + "\t" + empleado.getRUC_empleado() + "\t" + empleado.getNombre_empleado() + "\t" + empleado.getTelefono_empleado());
        }
        tbl_listaEmpleados.setModel(model);

    }

    private void limpiarCampos() {
        txt_idEmpleado.setText("");
        txt_nombresEmpleado.setText("");
        txt_rucEmpleados.setText("");
        txt_telefonoEmpleado.setText("");

    }

    private void agregarEmpleado() {
        try {
            String RUC = txt_rucEmpleados.getText();
            String nombre = txt_nombresEmpleado.getText();
            String telefono = txt_telefonoEmpleado.getText();

            Empleado nuevoEmpleado = new Empleado(0, RUC, nombre, telefono);
            if (empleadoDAO.agregarElmpleado(nuevoEmpleado)) {
                cargarEmpleado();
                limpiarCampos();
                //Muestra una ventana de dialogo con el mensaje 
                JOptionPane.showMessageDialog(null, "Se agregó el cliente correctamente");
            } else //Muestra una ventana de dialogo con el mensaje
            {
                JOptionPane.showMessageDialog(null, "No se pudo agregar el cliente");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void actualizarEmpleado() {
        int id = Integer.parseInt(txt_idEmpleado.getText());
        String RUC = txt_rucEmpleados.getText();
        String nombre = txt_nombresEmpleado.getText();
        String telefono = txt_telefonoEmpleado.getText();

        Empleado empleadoActualizado = new Empleado(id, RUC, nombre, telefono);
        if (empleadoDAO.actualizarEmpleado(empleadoActualizado)) {
            cargarEmpleado();
            limpiarCampos();
            btn_actualizarEmpleado.setVisible(false);
            btn_añadirEmpleado.setVisible(true);
            btn_eliminarEmpleado.setVisible(false);
            lbl_idEmpleado.setVisible(false);
            txt_idEmpleado.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se actualizó el cliente correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el cliente");
        }

    }

    private void eliminarEmpleado() {
        int id = Integer.parseInt(txt_idEmpleado.getText());
        if (empleadoDAO.eliminarEmpleado(id)) {
            cargarEmpleado();
            limpiarCampos();
            btn_actualizarEmpleado.setVisible(false);
            btn_añadirEmpleado.setVisible(true);
            btn_eliminarEmpleado.setVisible(false);
            lbl_idEmpleado.setVisible(false);
            txt_idEmpleado.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se eliminó el cliente correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el cliente");
        }

    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarEmpleado;
    private javax.swing.JButton btn_añadirEmpleado;
    private javax.swing.JButton btn_eliminarEmpleado;
    private java.awt.Button btn_regresarEmpleados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label5;
    private java.awt.Label lbl_idEmpleado;
    private java.awt.Label lbl_nombresEmpleado;
    private java.awt.Label lbl_rucEmpleado;
    private java.awt.Label lbl_telefonoEmpleado;
    private javax.swing.JTable tbl_listaEmpleados;
    private java.awt.TextField txt_idEmpleado;
    private java.awt.TextField txt_nombresEmpleado;
    private java.awt.TextField txt_rucEmpleados;
    private java.awt.TextField txt_telefonoEmpleado;
    // End of variables declaration//GEN-END:variables
}
