/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_peluqueria;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class ProductosView extends javax.swing.JFrame {

    private ProductoDAO productoDAO;
    private DefaultTableModel model;
    DecimalFormat df = new DecimalFormat("#.00");

    /**
     * Creates new form ProductosView
     */
    public ProductosView() {
        initComponents();
        btn_actualizarProducto.setVisible(false);
        txt_idProducto.setVisible(false);
        lbl_idProducto.setVisible(false);
        btn_eliminarProducto.setVisible(false);
        setLocationRelativeTo(null);
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_codigoProducto = new javax.swing.JLabel();
        lbl_nombreProducto = new javax.swing.JLabel();
        lbl_precioProducto = new javax.swing.JLabel();
        lbl_stockProducto = new javax.swing.JLabel();
        lbl_idProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_codigoProducto = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_listaProductos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_idProducto = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_nombreProducto = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_precioProducto = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_stockProducto = new javax.swing.JTextPane();
        btn_añadirProducto = new javax.swing.JButton();
        btn_actualizarProducto = new javax.swing.JButton();
        btn_eliminarProducto = new javax.swing.JButton();
        btn_regresarProducto = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jLabel1.setText("REGISTRO DE PRODUCTOS");

        lbl_codigoProducto.setText("Código:");

        lbl_nombreProducto.setText("Nombre:");

        lbl_precioProducto.setText("Precio:");

        lbl_stockProducto.setText("Stock en existencia:");

        lbl_idProducto.setText("ID:");

        jScrollPane1.setViewportView(txt_codigoProducto);

        tbl_listaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_listaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_listaProductos);

        jScrollPane3.setViewportView(txt_idProducto);

        jScrollPane4.setViewportView(txt_nombreProducto);

        jScrollPane5.setViewportView(txt_precioProducto);

        jScrollPane6.setViewportView(txt_stockProducto);

        btn_añadirProducto.setText("Añadir");
        btn_añadirProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirProductoMouseClicked(evt);
            }
        });

        btn_actualizarProducto.setText("Actualizar");
        btn_actualizarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarProductoMouseClicked(evt);
            }
        });

        btn_eliminarProducto.setText("Eliminar");
        btn_eliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarProductoMouseClicked(evt);
            }
        });

        btn_regresarProducto.setLabel("Regresar");
        btn_regresarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarProductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_eliminarProducto)
                                .addGap(18, 18, 18)
                                .addComponent(btn_actualizarProducto)
                                .addGap(18, 18, 18)
                                .addComponent(btn_añadirProducto))
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_stockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idProducto)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_codigoProducto)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nombreProducto)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbl_precioProducto))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_stockProducto))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_añadirProducto)
                    .addComponent(btn_actualizarProducto)
                    .addComponent(btn_eliminarProducto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btn_regresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarProductoMouseClicked
        // TODO add your handling code here:
        eliminarProducto();
    }//GEN-LAST:event_btn_eliminarProductoMouseClicked

    private void btn_actualizarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarProductoMouseClicked
        // TODO add your handling code here:
        actualizarProducto();
    }//GEN-LAST:event_btn_actualizarProductoMouseClicked

    private void btn_añadirProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirProductoMouseClicked
        // TODO add your handling code here:
        agregarProducto();
    }//GEN-LAST:event_btn_añadirProductoMouseClicked

    private void tbl_listaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listaProductosMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada = tbl_listaProductos.rowAtPoint(evt.getPoint());
        txt_idProducto.setText(String.valueOf(tbl_listaProductos.getValueAt(fila_seleccionada, 0)));
        txt_codigoProducto.setText(String.valueOf(tbl_listaProductos.getValueAt(fila_seleccionada, 1)));
        txt_nombreProducto.setText(String.valueOf(tbl_listaProductos.getValueAt(fila_seleccionada, 2)));
        txt_precioProducto.setText(String.valueOf(tbl_listaProductos.getValueAt(fila_seleccionada, 3)));
        txt_stockProducto.setText(String.valueOf(tbl_listaProductos.getValueAt(fila_seleccionada, 4)));
        btn_actualizarProducto.setVisible(true);
        btn_eliminarProducto.setVisible(true);
        btn_añadirProducto.setVisible(false);
        txt_idProducto.setVisible(true);
        lbl_idProducto.setVisible(true);
    }//GEN-LAST:event_tbl_listaProductosMouseClicked

    private void btn_regresarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarProductoMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_regresarProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    private void cargarProductos() {
        String[] columnNames = {"Id","Código int", "Nombre", "Precio", "Stock"};
        model = new DefaultTableModel(columnNames, 0);
        productoDAO = new ProductoDAO();

        List<Producto> productos = new ArrayList<>();
        productos = productoDAO.obtenerTodosProductos();
        for (Producto producto : productos) {
            model.addRow(new Object[]{producto.getId_producto(), producto.getCodigo_producto(), producto.getNombre_producto(), df.format(producto.getPrecio_producto()), producto.getStock_producto()});           
        }
        tbl_listaProductos.setModel(model);

    }

    private void limpiarCampos() {
        txt_idProducto.setText("");
        txt_codigoProducto.setText("");
        txt_nombreProducto.setText("");
        txt_precioProducto.setText("");
        txt_stockProducto.setText("");

    }

    private void agregarProducto() {
        try {
            String codigo = txt_codigoProducto.getText();
            String nombre = txt_nombreProducto.getText();
            double precio = Double.parseDouble(txt_precioProducto.getText());
            int stock = txt_stockProducto.getX();

            Producto nuevoProducto = new Producto(0, codigo, nombre, precio, stock);
            if (productoDAO.agregarProducto(nuevoProducto)) {
                cargarProductos();
                limpiarCampos();
                //Muestra una ventana de dialogo con el mensaje 
                JOptionPane.showMessageDialog(null, "Se agregó el producto correctamente");
            } else {
                //Muestra una ventana de dialogo con el mensaje
                JOptionPane.showMessageDialog(null, "No se pudo agregar el producto");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void actualizarProducto() {
        int id = Integer.parseInt(txt_idProducto.getText());
        String codigo = txt_codigoProducto.getText();
        String nombre = txt_nombreProducto.getText();
        double precio = Double.parseDouble(txt_precioProducto.getText());
        int stock = txt_stockProducto.getX();

        Producto productoActualizado = new Producto(id, codigo, nombre, precio,stock);
        if (productoDAO.actualizarProducto(productoActualizado)) {
            cargarProductos();
            limpiarCampos();
            btn_actualizarProducto.setVisible(false);
            btn_añadirProducto.setVisible(true);
            btn_eliminarProducto.setVisible(false);
            lbl_idProducto.setVisible(false);
            txt_idProducto.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se actualizó el producto correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el producto");
        }

    }

    private void eliminarProducto() {
        int id = Integer.parseInt(txt_idProducto.getText());
        if (productoDAO.eliminarProducto(id)) {
            cargarProductos();
            limpiarCampos();
            btn_actualizarProducto.setVisible(false);
            btn_añadirProducto.setVisible(true);
            btn_eliminarProducto.setVisible(false);
            lbl_idProducto.setVisible(false);
            txt_idProducto.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se eliminó el cliente correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el cliente");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarProducto;
    private javax.swing.JButton btn_añadirProducto;
    private javax.swing.JButton btn_eliminarProducto;
    private java.awt.Button btn_regresarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbl_codigoProducto;
    private javax.swing.JLabel lbl_idProducto;
    private javax.swing.JLabel lbl_nombreProducto;
    private javax.swing.JLabel lbl_precioProducto;
    private javax.swing.JLabel lbl_stockProducto;
    private javax.swing.JTable tbl_listaProductos;
    private javax.swing.JTextPane txt_codigoProducto;
    private javax.swing.JTextPane txt_idProducto;
    private javax.swing.JTextPane txt_nombreProducto;
    private javax.swing.JTextPane txt_precioProducto;
    private javax.swing.JTextPane txt_stockProducto;
    // End of variables declaration//GEN-END:variables
}
