/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_peluqueria;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casa
 */
public class UsuariosView extends javax.swing.JFrame {

    private TipoUsuarioDAO tipoUsuarioDAO;
    private UsuarioDAO usuarioDAO;
    private DefaultTableModel model;
    DefaultComboBoxModel modelo_comboBox;

    /**
     * Creates new form UsuariosView
     */
    public UsuariosView() {
        initComponents();
        btn_actualizarUsuario.setVisible(false);
        txt_idUsuario.setEnabled(false);
        txt_idUsuario.setVisible(false);
        lbl_idUsuario.setVisible(false);
        btn_eliminarUsuario.setVisible(false);
        setLocationRelativeTo(null);
        cargarTipoUsuario(cbx_tipoUsuario);
        cargarUsuarios();
        tipoUsuarioDAO = new TipoUsuarioDAO();
        usuarioDAO = new UsuarioDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_idUsuario = new java.awt.TextField();
        txt_nombreUsuario = new java.awt.TextField();
        txt_correoUsuario = new java.awt.TextField();
        lbl_idUsuario = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listaUsuarios = new javax.swing.JTable();
        label5 = new java.awt.Label();
        cbx_tipoUsuario = new javax.swing.JComboBox<>();
        txt_contraseñaUsusario = new javax.swing.JPasswordField();
        label1 = new java.awt.Label();
        btn_actualizarUsuario = new javax.swing.JButton();
        btn_eliminarUsuario = new javax.swing.JButton();
        btn_añadirUsuario = new javax.swing.JButton();
        btn_regresarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreUsuarioActionPerformed(evt);
            }
        });

        lbl_idUsuario.setText("ID:");

        label2.setText("Nombre y Apellido:");

        label3.setText("Contraseña:");

        label4.setText("Correo:");

        tbl_listaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_listaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_listaUsuarios);

        label5.setText("Tipo de Usuario:");

        cbx_tipoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_tipoUsuarioItemStateChanged(evt);
            }
        });
        cbx_tipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipoUsuarioActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("REGISTRO DE USUARIOS");

        btn_actualizarUsuario.setText("Actualizar");
        btn_actualizarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarUsuarioMouseClicked(evt);
            }
        });

        btn_eliminarUsuario.setText("Eliminar");
        btn_eliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarUsuarioMouseClicked(evt);
            }
        });

        btn_añadirUsuario.setText("Añadir");
        btn_añadirUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirUsuarioMouseClicked(evt);
            }
        });

        btn_regresarUsuario.setText("Regresar");
        btn_regresarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_idUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_correoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbx_tipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, 268, Short.MAX_VALUE)
                            .addComponent(txt_contraseñaUsusario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_regresarUsuario)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_eliminarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(btn_actualizarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(btn_añadirUsuario)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_correoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_contraseñaUsusario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizarUsuario)
                    .addComponent(btn_eliminarUsuario)
                    .addComponent(btn_añadirUsuario))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_regresarUsuario))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreUsuarioActionPerformed

    private void cbx_tipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipoUsuarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbx_tipoUsuarioActionPerformed

    private void cbx_tipoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_tipoUsuarioItemStateChanged
        cbx_tipoUsuario.getSelectedIndex();
    }//GEN-LAST:event_cbx_tipoUsuarioItemStateChanged

    private void tbl_listaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada = tbl_listaUsuarios.rowAtPoint(evt.getPoint());
        txt_idUsuario.setText(String.valueOf(tbl_listaUsuarios.getValueAt(fila_seleccionada, 0)));
        txt_nombreUsuario.setText(String.valueOf(tbl_listaUsuarios.getValueAt(fila_seleccionada, 1)));
        txt_correoUsuario.setText(String.valueOf(tbl_listaUsuarios.getValueAt(fila_seleccionada, 2)));
        txt_contraseñaUsusario.setText(String.valueOf(usuarioDAO.seleccionarPassword(Integer.parseInt(String.valueOf(tbl_listaUsuarios.getValueAt(fila_seleccionada, 0))))));

        btn_actualizarUsuario.setVisible(true);
        btn_eliminarUsuario.setVisible(true);
        btn_añadirUsuario.setVisible(false);
        txt_idUsuario.setVisible(true);
        lbl_idUsuario.setVisible(true);
    }//GEN-LAST:event_tbl_listaUsuariosMouseClicked

    private void btn_eliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarUsuarioMouseClicked
        // TODO add your handling code here:
        eliminarUsuario();
    }//GEN-LAST:event_btn_eliminarUsuarioMouseClicked

    private void btn_actualizarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarUsuarioMouseClicked
        // TODO add your handling code here:
        actualizarUsuario();
    }//GEN-LAST:event_btn_actualizarUsuarioMouseClicked

    private void btn_añadirUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirUsuarioMouseClicked
        // TODO add your handling code here:
        agregarUsuarios();
    }//GEN-LAST:event_btn_añadirUsuarioMouseClicked

    private void btn_regresarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarUsuarioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_regresarUsuarioMouseClicked

    private void cargarTipoUsuario(JComboBox c) {
        DefaultComboBoxModel combobox_modelo_tipo_usuario = new DefaultComboBoxModel();
        tipoUsuarioDAO = new TipoUsuarioDAO();

        List<TipoUsuario> tipoUsuarios = new ArrayList<>();
        tipoUsuarios = tipoUsuarioDAO.obtenerTipoUsusarios();
        ComboBoxItemTipoUsuarios tipo_usuario = new ComboBoxItemTipoUsuarios("0", "seleccione");
        combobox_modelo_tipo_usuario.addElement(tipo_usuario);
        for (TipoUsuario tipoUsuario : tipoUsuarios) {
            tipo_usuario = new ComboBoxItemTipoUsuarios(String.valueOf(tipoUsuario.getId_tipoUsuario()), tipoUsuario.getTipoUsuario());
            combobox_modelo_tipo_usuario.addElement(tipo_usuario);
        }
        c.setModel(combobox_modelo_tipo_usuario);

    }

    private void cargarUsuarios() {
        String[] columnNames = {"ID","Nombre", "Correo", "Tipo"};
        model = new DefaultTableModel(columnNames, 0);
        usuarioDAO = new UsuarioDAO();

        List<Usuario> usuarios = new ArrayList<>();
        usuarios = usuarioDAO.obtenerTodosUsusarios();
        for (Usuario usuario : usuarios) {
            model.addRow(new Object[]{usuario.getId_usuario(), usuario.getNombre_usuario(), usuario.getCorreo_usuario(), tipoUsuarioDAO.buscarUsuarioPorId(usuario.getId_tipoUsuario())});
            
        }
        tbl_listaUsuarios.setModel(model);

    }

    private void limpiarCampos() {
        txt_idUsuario.setText("");
        txt_nombreUsuario.setText("");
        txt_correoUsuario.setText("");
        txt_contraseñaUsusario.setText("");

    }

    private void agregarUsuarios() {
        try {
            String nombre = txt_nombreUsuario.getText();
            String correo = txt_correoUsuario.getText();
            String contraseña = new String(txt_contraseñaUsusario.getPassword());

            ComboBoxItemTipoUsuarios tipo_usuario_seleccioando = (ComboBoxItemTipoUsuarios) cbx_tipoUsuario.getSelectedItem();
            String id_tipoUsuario_seleccionado = tipo_usuario_seleccioando.getClave();
            int tipo = Integer.parseInt(id_tipoUsuario_seleccionado);

            Usuario nuevoUsuario = new Usuario(0, nombre, correo, contraseña, tipo);
            if (usuarioDAO.agregarUsuario(nuevoUsuario)) {
                cargarUsuarios();
                limpiarCampos();
                //Muestra una ventana de dialogo con el mensaje 
                JOptionPane.showMessageDialog(null, "Se agregó el usuario correctamente");
            } else {
                //Muestra una ventana de dialogo con el mensaje
                JOptionPane.showMessageDialog(null, "No se pudo agregar el usuario");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void actualizarUsuario() {

        int id = Integer.parseInt(txt_idUsuario.getText());
        String nombre = txt_nombreUsuario.getText();
        String correo = txt_correoUsuario.getText();
        String contraseña = new String(txt_contraseñaUsusario.getPassword());

        ComboBoxItemTipoUsuarios tipo_usuario_seleccioando = (ComboBoxItemTipoUsuarios) cbx_tipoUsuario.getSelectedItem();
        String id_tipoUsuario_seleccionado = tipo_usuario_seleccioando.getClave();
        int tipo = Integer.parseInt(id_tipoUsuario_seleccionado);

        Usuario usuarioActualizado = new Usuario(id, nombre, correo, contraseña, tipo);
        if (usuarioDAO.actualizarUsuario(usuarioActualizado)) {
            cargarUsuarios();
            limpiarCampos();
            btn_actualizarUsuario.setVisible(false);
            btn_añadirUsuario.setVisible(true);
            btn_eliminarUsuario.setVisible(false);
            lbl_idUsuario.setVisible(false);
            txt_idUsuario.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se actualizó el usuario correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el usuario");
        }

    }

    private void eliminarUsuario() {
        int id = Integer.parseInt(txt_idUsuario.getText());
        if (usuarioDAO.eliminarUsuario(id)) {
            cargarUsuarios();
            limpiarCampos();
            btn_actualizarUsuario.setVisible(false);
            btn_añadirUsuario.setVisible(true);
            btn_eliminarUsuario.setVisible(false);
            lbl_idUsuario.setVisible(false);
            txt_idUsuario.setVisible(false);
            //Muestra una ventana de dialogo con el mensaje 
            JOptionPane.showMessageDialog(null, "Se eliminó el usuario correctamente");
        } else {
            //Muestra una ventana de dialogo con el mensaje
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el usuario");
        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarUsuario;
    private javax.swing.JButton btn_añadirUsuario;
    private javax.swing.JButton btn_eliminarUsuario;
    private javax.swing.JButton btn_regresarUsuario;
    private javax.swing.JComboBox<String> cbx_tipoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label lbl_idUsuario;
    private javax.swing.JTable tbl_listaUsuarios;
    private javax.swing.JPasswordField txt_contraseñaUsusario;
    private java.awt.TextField txt_correoUsuario;
    private java.awt.TextField txt_idUsuario;
    private java.awt.TextField txt_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
